### ISSUE TITLE
[FR] Optical align

### ISSUE THREAD

**Issue by barmallion** [HugoLis/Magic-Aligner#1]
Hi! Can you add optical align feature?
![image](https://user-images.githubusercontent.com/17190030/70039240-a5f38b00-15ca-11ea-91f1-ddd75389fb83.png)

**Comment by HugoLis** [comment]
Hi, barmallion. Thank you for leaving feedback.

In the cases you showed, I believe the problem was that the bounding box you used was not accurate. For some reason, sketch does that in some cases. Try to flatten the layer before using Magic Aligner, like in the GIF below.

Magic Aligner usually works great with objects that have radial symmetry, like this star and equilateral triangles.

Anyway, if you want to understand more about the plugin, here is a blog post I wrote about it: http://hugolispector.com/magic-aligner/

![magic-aligner](https://user-images.githubusercontent.com/33968615/70050873-ba298f00-15ae-11ea-9ba3-316e699a1e33.gif)

**Comment by barmallion** [comment]
All shapes in my screenshot is already flatten. 
![image](https://user-images.githubusercontent.com/17190030/70052969-828a0980-15e5-11ea-8a1e-cf06eabb1ab7.png)

**Comment by barmallion** [comment]
After flattening and move to center of artboard - star is not optically centered. Triangle too.

**Comment by barmallion** [comment]
Left to right: 1 - Hand, 2 - Sketch, 3 - Magic Aligner

**Comment by HugoLis** [comment]
Optical alignment is subjective. This plugin uses the center of mass approach, which is suitable for many cases, but not all of them. Regardless, Magic Aligner can provide great insight and serve as a base for further adjustments.

![magic-aligner2](https://user-images.githubusercontent.com/33968615/70055036-79824380-15b7-11ea-9552-2a8c3c6c60d4.gif)

**Comment by barmallion** [comment]
I understand my problem - need center initially and after this use plugin. Sorry.
