### ISSUE TITLE
Object keep moving to the right side

### ISSUE THREAD

**Issue by Raghav789** [HugoLis/Magic-Aligner#2]
I did a simple play button test (a circle with a triangle inside ) every time I run 'Align to center mass' the object keep shifting/nudging to the right side ( X-axis ) even though it's already Align to center mass at the first attempt.

**Comment by HugoLis** [comment]
What you have described is the expected behavior. Please remember the usage instructions:
   - Center objects by their bounding boxes
   - Select an object
   - Go to "Plugins > Magic Aligner > Align to Center of Mass ⌘ + L"

![gif](https://user-images.githubusercontent.com/33968615/71357137-5e29a900-2563-11ea-87ab-42c5a5fde974.gif)
